### ISSUE TITLE
Gosu::GSKWindow (NameError)

### ISSUE THREAD

**Issue by ghost** [gosu/motion-gosu#4]
Hi,

I'm running motion-gosu along with RubyMotion. 

When I build my project to run on Xcode's iPhone 6s simulator, the simulator starts but then crashes and I get this error message:

/Users/Nitish/.rvm/gems/ruby-2.4.0/bundler/gems/motion-gosu-f08ae90be01e/motion/window.rb:2:in `<ma: uninitialized constant Gosu::GSKWindow (NameError)
from /Users/Nitish/.rvm/gems/ruby-2.4.0/bundler/gems/motion-gosu-f08ae90be01e/motion/window.rb:78:in 

There seems to be an issue with the reference to GSKWindow?

Any help would be appreciated.

Thanks.

**Comment by jlnr** [comment]
Hey, thanks for checking out motion-gosu. I'm sorry that the documentation is still terrible, but I've taken the time to update Gosu, motion-gosu, and my undocumented example game [Trikus](https://github.com/jlnr/Trikus) to make sure they all work together again.

So, looking at your error message, I think you are somehow running your game in the wrong way because RVM should not be involved in RubyMotion running on an iOS simulator. I recommend that you check out Trikus and then try the following steps:

- Run Trikus using normal Ruby/Gosu by running `bundle`, then `ruby trikus.rb`. Don't worry about the game itself, but you should see a window with some colorful board game pieces.
- Now run Trikus using RubyMotion for macOS:
```bash
cd osx
bundle # installs motion-gosu and other stuff that will run on your Mac
bundle exec rake pod:install # installs Gosu, motion-gosu and other stuff that will run in your app
bundle exec rake # build and run Trikus for macOS using RubyMotion
```
- If that works, retry the same three `bundle` commands from inside the `ios` directory.

If this works, then you can look at how Trikus organizes its source code for easy building with RubyMotion. This is what you will have to do for your game as well.

**Comment by ghost** [comment]
Thank you for your help. The above worked with my project.
