### ISSUE TITLE
Help Needed - TextInput Initialisation Failures in motion-gosu

### ISSUE THREAD

**Issue by ghost** [gosu/motion-gosu#6]
Hi,

I'm trying to initialise Gosu::TextInput in my motion-gosu app, but I'm getting uninitialized constant Gosu::TextInput (NameError) for some reason. Not sure as to why this is as initialisation of other classes such as Gosu::Image initialise fine and they are in the same place for where I'm trying to initialise TextInput. Not sure if I'm missing something here?

Any help will be appreciated. 

Thanks.

**Comment by jlnr** [comment]
Hey, ... ummm, bad news: Gosu::TextInput does not work on iOS yet (maybe not even on macOS with gosu-motion, but that would be easy to fix).

The quickest workaround is to use [UIAlertView with text fields](https://stackoverflow.com/a/34504458) to query the user for input instead. Is that viable? I'll also look at how much work it would be to implement TextInput.

**Comment by ghost** [comment]
Hi,

Ah, ok :-(

Hmmm, I would prefer to use motion-gosu code for consistency. Would it be possible for you to give a rough estimate on when TextInput in motion-gosu will be ready by please? I have other areas of my app I can work on in the meantime.

Thanks.

**Comment by jlnr** [comment]
Good question. I hope to hack on Gosu again in the next two days. Maybe that'll be enough for a first implementation :) The irony is that I introduced the TextInput class specifically for Gosu's iOS port, and then never ported it. That alone annoys me enough that I'll prioritize this ticket.

**Comment by ghost** [comment]
Ok, that sounds good.

Hahaha we've all done similar things. Thanks for prioritising this ticket.

**Comment by jlnr** [comment]
OK, I've started and I think I have a pretty good idea of what needs to be done. I hope it'll be somewhat usable by the weekend.

**Comment by jlnr** [comment]
- [ ] Make TextInput.cpp compile on iOS too
- [ ] Implement UITextInput protocol in GosuGLView (deferring to current TextInput instance)
- [ ] Make TextInput available in motion-gosu (macOS)
- [ ] Make TextInput available in motion-gosu (iOS if extra work is needed?)

**Comment by ghost** [comment]
Ok thanks. Much appreciated! I'll look forward to seeing the implementation.

**Comment by jlnr** [comment]
Turns out I was overthinking this. Instead of implementing the full `UITextInput` protocol, I went for the simpler `UIKeyInput` and that was a breeze.

I have updated both Gosu and motion-gosu, so you'll need to update both from git master for this to work. The motion-gosu repository now also contains [an example project](https://github.com/gosu/motion-gosu/tree/master/example) that is easier to follow than Trikus. (I'll set the Trikus repository to private for now, it's too messy.)

I've successfully tested TextInput on iOS with this adapted example: https://gist.github.com/jlnr/230772c4a0b54c7edc4007430aec72af
